apiVersion: v1
kind: Service
metadata:
  labels:
    app: shypple
  name: shypple
spec:
  ports:
  - name: 8000-tcp
    port: 8000
  selector:
    deployment: shypple
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: shypple
  name: shypple
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: shypple
  template:
    metadata:
      labels:
        deployment: shypple
    spec:
      containers:
      - name: shypple
        image: ghcr.io/manish-jangra/django-markdown-editor:master
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          protocol: TCP
      restartPolicy: Always